name: NPM publish
on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Publish to npm
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
              run: |
                  npm config set "//registry.npmjs.org/:_authToken" "${NPM_AUTH_TOKEN}"
                  yarn
                  npm publish
